### DISCUSSION TITLE
Setting up Traction

### DISCUSSION THREAD

**Discussion by cooldude4u** [bcgov/traction#1604] [Q&A]
Hi everyone,
I just want to know what the purpose of the traction-acapy database is. It seems to stay empty — is that expected?

**Comment by loneil** [comment]
Yeah looks like locally it's just a blank database that the Postgres image in the docker compose environment

```
  traction-db:
    image: "postgres:15"
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    ports:
      - ${POSTGRESQL_PORT}:5432
    volumes:
      - traction-wallet:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    extra_hosts:
      - host.docker.internal:host-gateway
```

That POSTGRESQL_DB takes from .env which we just default to `traction_acapy` so I believe it's just unused (maybe unnecessary)
