### ISSUE TITLE
Set default endorser in helm value

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#1376]
In `values.yaml` the ledger/endorser default setup is

```
  ## Acapy multiledger configuration file
  ## @param acapy.ledgers.yml [object] YAML configuration for connecting to multiple HyperLedger
  ##
  ledgers.yml:
    - id: bcovrin-test
      is_production: true
      is_write: true
      genesis_url: "http://test.bcovrin.vonx.io/genesis"
      endorser_did: "Ket75eV5UQvVkW2XBjgDH7"
      endorser_alias: "bcovrin-test-endorser"
```

Ket75eV5UQvVkW2XBjgDH7 is not a valid endorser any more (was the old one in tools).

Should set this to one that can be used? I think? Is it ok for us to put the DID for our auto-everything sandbox bcovrin-test endorser in here as default config? cc @esune
