### ISSUE TITLE
Certificate authority problem during oc-login action to deploy to OCP

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#1548]
We've started getting failures on deploy step for pull requests or merge to main this week 

```
Run redhat-actions/oc-login@v1
  with:
    openshift_server_url: ***
    openshift_token: ***
    certificate_authority_data: ***
    namespace: ***
    insecure_skip_tls_verify: false
    reveal_cluster_name: false
Authenticating using token
Writing out certificate authority data to /home/runner/work/traction/traction/openshift-ca.crt
/home/runner/work/_temp/openshift-bin/oc login --token=*** --server=*** --certificate-authority=/home/runner/work/traction/traction/openshift-ca.crt
error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
Error: Error: oc exited with code 1
error: The server uses a certificate signed by unknown authority. You may need to use the --certificate-authority flag to provide the path to a certificate file for the certificate authority, or --insecure-skip-tls-verify to bypass the certificate check and use insecure connections.
```

Example fail:
https://github.com/bcgov/traction/actions/runs/14115573493/job/39545698759?pr=1547

This happens in the `deploy` stage in the OC login part of the step
```
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
```

I commented out `certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}` and the PR deployment worked.

Looks like we are supplying a CA Cert that got outdated recently? As part of the SSL certificate update to the cluster. And we don't need to use this because the certs available for the OCP API url are from a public CA.

So can 
1. Remove the `certificate_authority_data` field from the **oc-login** action in `on_pr_closed`, `on_pr_opened`, and `on_push_main`
2. Confirm nothing else uses `secrets.OPENSHIFT_CA_CRT` and delete the secret from the repo so it's not hanging around
