### ISSUE TITLE
Deploy traction and tenant-ui alpha to e79518-dev (Digital Trust)

### ISSUE THREAD

**Issue by usingtechnology** [bcgov/traction#468]
No CICD, manually deploy.

Smoke test the current helm charts in bcgov/traction, make changes as needed. 
Provide documentation for @WadeBarnes to run the charts from his desktop to the target namespace.

Start with traction only, add tenant-ui once traction is deployed successfully.

**Comment by usingtechnology** [comment]
attaching a readme + values yaml file

[Traction Helm Charts Deployment.zip](https://github.com/bcgov/traction/files/10736990/Traction.Helm.Charts.Deployment.zip)

**Comment by usingtechnology** [comment]
# Traction Helm Charts Deployment

#### Dependencies

1. Openshift `oc` command line tools (version 4.7)
2. Helm command line tools (v3.6.2)
3. Admin access to an Openshift namespace (ex. e79518-dev).


### Helm Charts

Clone traction repository, go to traction charts and create a new file for your values.  

```sh
git clone https://github.com/bcgov/traction.git
cd traction/charts/traction
cat > values-e79518-dev.yaml
<paste in contents>
```

#### values-e79518-dev.yaml contents
```yaml
global:
  ingressSuffix: -dev.apps.silver.devops.gov.bc.ca
acapy:
  image:
    tag: "ghcr.io/bcgov/traction-plugins-acapy:sha-03b72fc"
    version: 'sha-03b72fc'
    buildtime: '2023-02-13T21:12:08.001Z'
    pullPolicy: Always
  secret:
    adminurl:
      generated: false
    pluginInnkeeper:
      generated: false
  pluginValues:
    tractionInnkeeper:
      printKey: true
      printToken: true
  tails:
    enabled: true
tenant_proxy:
  image:
    tag: "ghcr.io/bcgov/traction-tenant-proxy:sha-03b72fc"
    version: 'sha-03b72fc'
    buildtime: "2023-02-13T21:12:09.053Z"
    pullPolicy: Always
```


### Deploy

1. In a browser, login to your Openshift namespace, copy your login command
2. At a command prompt, paste your login command and execute. Log in to Openshift.
3. Ensure you are in the correct project/namespace
4. Navigate to the root of your traction repository
5. Execute helm commands

#### Dry Run
It is advisable to do a dry run and examine the output to see if it works and if there are any noticeable mistakes in resource naming, url formation etc.  This is the same call as the install/upgrade but with the `--dry-run` flag added.

```sh
helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-e79518-dev.yaml traction ./charts/traction --install --wait --dry-run
```

#### Install/Upgrade
The following can be used to install (if helm project does not exists) or rollout changes (ex. new configuration, new image).

`traction` is the name of the helm project.

```sh
helm upgrade -f ./charts/traction/values.yaml -f ./charts/traction/values-e79518-dev.yaml traction ./charts/traction --install --wait 
```

#### Remove/Delete
Removal of all the resources created is a 2 step process: 

1. uninstall the helm project
2. remove secrets and storage

```sh
helm uninstall traction
oc delete secret,pvc --selector "app.kubernetes.io/instance"=traction
```
