### ISSUE TITLE
Postgres tuning for high request volume

### ISSUE THREAD

**Issue by esune** [bcgov/traction#558]
As per conversation with @usingtechnology :

It appears that Postgres might not be able to handle swarms of connections by default: the issue was uncovered while attempting to create several tenants programatically. When hitting 20 concurrent requests (each tenant will create its db schema), Postgres throws the following error:
```
sorry, too many clients already
```

The issue was overcome by using a custom `max_conns.sql` with the following contents:
```
ALTER SYSTEM SET max_connections = 500;
```

In docker, the mount path is as outlined in the following snippet (might be different in k8s/OpenShift):
```
wallet-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    ports:
      - 5433:5432
    volumes:
      - wallet-db-data:/var/lib/pgsql/data
      - ./max_conns.sql:/docker-entrypoint-initdb.d/max_conns.sql    
    networks:
      - app-network
```

Acceptance Criteria:
- Add custom `max_conns.sql` configuration file/settings to the Postgres deployment used as dependency by Traction.
- 
-The better way to set the max connections on a Postgres server is to use the Postgres configuration files. We do this with the BC Registries databases. It was done specifically for the wallet (secure storage) in that case. Example here https://github.com/bcgov/von-bc-registries-agent-configurations/blob/main/openshift/templates/db/config/postgresql-cfg/dbconnections.conf. It might be an idea to adopt the configuration as standard for any wallet databases (secure storage).
