### ISSUE TITLE
[Helm Chart] Ledger and URLs should be set in Values.

### ISSUE THREAD

**Issue by i5okie** [bcgov/traction#712]
Currently, ledger selection is pre-determined within helper file.

Current ledger configuration in Values:
```
...
## @section Traction configuration
##
## @param config.ledger.name The ledger to be used.
## @param config.ledger.browserUrlOverride Overrides ledger browser url
## @param config.ledger.genesisUrlOverride Overrides genesis url
config:
  ledger: 
    name: bcovrin-test
    browserUrlOverride: ""
    genesisUrlOverride: ""
...
```

The [`.Values.config.ledger.name`](https://github.com/bcgov/traction/blob/main/charts/traction/values.yaml#L8-L17) (excerpt from Values above) expects one of three values (bcovrin-dev|bcovrin-test|idu) and substitutes the tails urls, and ledger browser with the mapped URLs.
E.g.:
`{{- $tailsBaseUrl := dict "bcovrin-dev" "https://tails-dev.vonx.io" "bcovrin-test" "https://tails-test.vonx.io" "idu" (printf "https://tails%s" .Values.ingressSuffix) -}}
`

The required variables should be provided via values overrides.
